config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :provisionings

  resources :servers do
    member do
      get :refresh
      get :provision
    end
  end

  root 'home#index'

end

app/models/server.rb
class Server
  include Mongoid::Document
  include Mongoid::Timestamps

  has_and_belongs_to_many :roles
  has_many :provisionings
  belongs_to :user

  field :name, type: String
  field :provider_id, type: String
  field :ip_address, type: String
  field :region, type: String
  field :cpus, type: Integer
  field :disk, type: Integer
  field :status, type: String
  field :size, type: String

  def system_id
    "srv_#{id}"
  end

  def user
    'root'
  end

  def type
  end

  def manage_url
  end

  def accessible?
  end

  def refresh!
  end

  def provision
  end
  handle_asynchronously :provision

  # This is needed to allow properly routing with inheritance :(
  def self.inherited(child)
    child.instance_eval do
      def model_name
        Server.model_name
      end
    end
    super
  end
end

app/controllers/servers_controller.rb
class ServersController < ApplicationController
  before_action :set_server, only: [:show, :edit, :update, :destroy, :refresh, :provision]
  before_action :set_roles, only: [:new, :create, :edit, :update]

  def provision
    @server.provision

    redirect_to :back
  end

  def refresh
    @server.refresh!

    redirect_to :back
  end

  # GET /servers
  # GET /servers.json
  def index
    @servers = current_user.servers.all
  end

  # GET /servers/1
  # GET /servers/1.json
  def show
  end

  # GET /servers/new
  def new
    @server = current_user.servers.new
  end

  # GET /servers/1/edit
  def edit
  end

  # POST /servers
  # POST /servers.json
  def create
    @server = ServerFactory.create_server(server_params, params[:api_key])
    @server.user = current_user

    respond_to do |format|
      if @server.save
        format.html { redirect_to @server, notice: 'Server was successfully created.' }
        format.json { render :show, status: :created, location: @server }
      else
        format.html { render :new }
        format.json { render json: @server.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /servers/1
  # PATCH/PUT /servers/1.json
  def update
    respond_to do |format|
      if @server.update(server_params)
        format.html { redirect_to @server, notice: 'Server was successfully updated.' }
        format.json { render :show, status: :ok, location: @server }
      else
        format.html { render :edit }
        format.json { render json: @server.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /servers/1
  # DELETE /servers/1.json
  def destroy
    @server.destroy
    respond_to do |format|
      format.html { redirect_to servers_url, notice: 'Server was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_server
      @server = current_user.servers.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def server_params
      params.require(:server).permit(:name, :region, :size, :image, role_ids: [])
    end
end

app/views/servers/_form.html.erb
<%= form_for(@server) do |f| %>
  <% if @server.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@server.errors.count, "error") %> prohibited this server from being saved:</h2>

      <ul>
      <% @server.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <h2>Account</h2>
  <div class="field">
    <%= text_field_tag :api_key %>
  </div>

  <h2>Associated roles</h2>
  <div class="field">
    <%= f.collection_check_boxes(:role_ids, @roles, :id, :name) %>
  </div>

  <h2>Server information</h2>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, value: 'new-server' %>
    <small>Only valid hostname characters are allowed. (a-z, A-Z, 0-9, . and -)</small>
  </div>
  <div class="field">
    <%= f.label :size %><br>
    <%= f.text_field :size, value: '512mb' %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
      <%= f.text_field :image, value: '5588928' %>
  </div>
  <div class="field">
    <%= f.label :region %><br>
    <%= f.text_field :region, value: 'ams2' %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/servers/edit.html.erb
<h1>Editing server</h1>

<%= render 'form' %>

<%= link_to 'Show', @server %> |
<%= link_to 'Back', servers_path %>

app/views/servers/index.html.erb
<h1>Listing servers</h1>

<table>
  <thead>
    <tr>
      <th>Type</th>
      <th>ID</th>
      <th>Name</th>
      <th>IP address</th>
      <th>Region</th>
      <th>Status</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @servers.each do |server| %>
      <tr>
        <td><%= server.type %></td>
        <td><%= server.provider_id %></td>
        <td><%= server.name %></td>
        <td><%= server.ip_address %></td>
        <td><%= server.region %></td>
        <td><%= server.status %></td>
        <td><%= link_to 'Manage', server.manage_url %></td>
        <td><%= link_to 'Refresh', refresh_server_path(server) %></td>
        <td><%= link_to 'Provision', provision_server_path(server) %></td>
        <td><%= link_to 'Show', server %></td>
        <td><%= link_to 'Edit', edit_server_path(server) %></td>
        <td><%= link_to 'Destroy', server, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Server', new_server_path %>

app/views/servers/new.html.erb
<h1>New server</h1>

<%= render 'form' %>

<%= link_to 'Back', servers_path %>

app/views/servers/show.html.erb
<p>
  <strong>Type:</strong>
  <%= @server.type %>
</p>

<p>
  <strong>Ip address:</strong>
  <%= @server.ip_address %>
</p>

<p>
  <strong>Region:</strong>
  <%= @server.region %>
</p>

<%= link_to 'Edit', edit_server_path(@server) %> |
<%= link_to 'Back', servers_path %>