config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :provisionings

  resources :servers do
    member do
      get :refresh
      get :provision
    end
  end

  root 'home#index'

end

app/models/provisioning.rb
class Provisioning
  include Mongoid::Document
  include Mongoid::Timestamps

  belongs_to :server
end

app/controllers/provisionings_controller.rb
class ProvisioningsController < ApplicationController
  before_action :set_provisioning, only: [:show, :edit, :update, :destroy]
  before_action :set_roles, only: [:new, :create, :edit, :update]

  # GET /provisionings
  # GET /provisionings.json
  def index
    @provisionings = Provisioning.all
  end

  # GET /provisionings/1
  # GET /provisionings/1.json
  def show
  end

  # GET /provisionings/new
  def new
    @provisioning = Provisioning.new
  end

  # GET /provisionings/1/edit
  def edit
  end

  # POST /provisionings
  # POST /provisionings.json
  def create
    @provisioning = Provisioning.new(provisioning_params)

    respond_to do |format|
      if @provisioning.save
        format.html { redirect_to @provisioning, notice: 'Provisioning was successfully created.' }
        format.json { render :show, status: :created, location: @provisioning }
      else
        format.html { render :new }
        format.json { render json: @provisioning.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /provisionings/1
  # PATCH/PUT /provisionings/1.json
  def update
    respond_to do |format|
      if @provisioning.update(provisioning_params)
        format.html { redirect_to @provisioning, notice: 'Provisioning was successfully updated.' }
        format.json { render :show, status: :ok, location: @provisioning }
      else
        format.html { render :edit }
        format.json { render json: @provisioning.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /provisionings/1
  # DELETE /provisionings/1.json
  def destroy
    @provisioning.destroy
    respond_to do |format|
      format.html { redirect_to provisionings_url, notice: 'Provisioning was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_provisioning
      @provisioning = Provisioning.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def provisioning_params
      params.require(:provisioning).permit(:role_ids)
    end
end

app/views/provisionings/_form.html.erb
<%= form_for(@provisioning) do |f| %>
  <% if @provisioning.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@provisioning.errors.count, "error") %> prohibited this provisioning from being saved:</h2>

      <ul>
      <% @provisioning.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/provisionings/edit.html.erb
<h1>Editing provisioning</h1>

<%= render 'form' %>

<%= link_to 'Show', @provisioning %> |
<%= link_to 'Back', provisionings_path %>

app/views/provisionings/index.html.erb
<h1>Listing provisionings</h1>

<table class="table">
  <thead>
    <tr>
      <th></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @provisionings.each do |provisioning| %>
      <tr>
        <td><%= provisioning.created_at %></td>
        <td><%= link_to 'Show', provisioning %></td>
        <td><%= link_to 'Edit', edit_provisioning_path(provisioning) %></td>
        <td><%= link_to 'Destroy', provisioning, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Provisioning', new_provisioning_path %>

app/views/provisionings/new.html.erb
<h1>New provisioning</h1>

<%= render 'form' %>

<%= link_to 'Back', provisionings_path %>

app/views/provisionings/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_provisioning_path(@provisioning) %> |
<%= link_to 'Back', provisionings_path %>